version: '3'
volumes:
  mysql_tourist:
services:
  mysql:
    image: mysql:8
    container_name: mysqlTourist
    environment:
      MYSQL_DATABASE: touristapirest
      MYSQL_USER: devgroup
      MYSQL_PASSWORD: TouristApp1@
      MYSQL_ROOT_PASSWORD: TouristApp1@
    ports:
      - '3307:3306'
    volumes:
      - mysql_tourist:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping --password=${MYSQL_ROOT_PASSWORD} -h localhost "
      timeout: 20s
      retries: 10
      interval: 10s
    restart: always
  touristbackend:
    build: ./TouristAppDockerizado
    image: touristapp
    #command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      mysql:
        condition: service_healthy