# Generated by Django 4.0.6 on 2022-10-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_negocio_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagen',
            field=models.ImageField(blank='', default='', upload_to='negocios/items/'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='imagen',
            field=models.ImageField(blank='', default='', upload_to='negocios/'),
        ),
    ]
